# Clase 5 - Python

In [1]:
import pandas as pd
import numpy as np
import mysql.connector

In [7]:
cnx = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "tQYCnFua9HvCN*E3",
    database = "football_db"
)

cursor = cnx.cursor()

query = 'SELECT * FROM football_db.appearances LIMIT 500;'

cursor.execute(query)

results = cursor.fetchall()

col_names = ['idappearances', 'goals', 'ownGoals', 'shots', 'xGoals', 
             'xGoalsChain', 'xGoalsBuildup', 'assist', 'keyPasses', 
             'xAssists', 'position', 'positionOrder', 'yellowCard', 
             'redCard', 'time', 'substituteIn', 'substituteOut', 
             'games_gamesID', 'players_playerID', 'leagues_leagueID']

data = pd.DataFrame(results, columns = col_names)

cnx.close()

In [9]:
df = data.copy()

In [10]:
df

,idappearances,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assist,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,games_gamesID,players_playerID,leagues_leagueID
0,1,0,0,0,0.000000,0.000000e+00,0.000000e+00,0,0,0.000000,GK,1,0,0,90,0,0,81,560,1
1,2,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,1,0.106513,DR,2,0,0,82,222605,0,81,557,1
2,3,0,0,0,0.000000,1.277380e-01,1.277380e-01,0,0,0.000000,DC,3,0,0,90,0,0,81,548,1
3,4,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,0,0.000000,DC,3,0,0,90,0,0,81,628,1
4,5,0,0,0,0.000000,2.122470e-02,2.122470e-02,0,0,0.000000,DL,4,0,0,90,0,0,81,1006,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,0,0,2,0.124260,2.644150e-01,1.401540e-01,0,0,0.000000,Sub,17,0,0,25,0,57403,98,966,1
496,497,0,0,0,0.000000,6.133210e-01,6.133210e-01,0,0,0.000000,GK,1,0,0,90,0,0,99,609,1
497,498,0,0,0,0.000000,9.684590e-02,9.684590e-02,0,0,0.000000,DR,2,0,0,90,0,0,99,625,1
498,499,0,0,1,0.358843,1.147160e+13,1.147160e+13,0,0,0.000000,DC,3,1,0,90,0,0,99,626,1
499,500,1,0,1,0.069107,8.224680e-01,8.224680e-01,0,0,0.000000,DC,3,1,0,90,0,0,99,612,1

In [15]:
df.drop_duplicates(['yellowCard','redCard','time','substituteIn'])

,idappearances,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assist,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,games_gamesID,players_playerID,leagues_leagueID
0,1,0,0,0,0.000000e+00,0.000000e+00,0.000000,0,0,0.000000,GK,1,0,0,90,0,0,81,560,1
1,2,0,0,0,0.000000e+00,1.065130e-01,0.106513,0,1,0.106513,DR,2,0,0,82,222605,0,81,557,1
6,7,0,0,0,0.000000e+00,3.574200e-02,0.000000,0,1,0.035742,DMC,7,0,0,61,222606,0,81,654,1
7,8,0,0,3,2.536450e-01,2.558110e-01,0.106513,0,0,0.000000,AMR,11,1,0,90,0,0,81,554,1
8,9,0,0,3,1.213090e-01,5.696670e-02,0.000000,0,0,0.000000,AMC,12,0,0,69,222607,0,81,555,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,480,0,0,1,1.361530e-01,8.811020e-02,0.088110,0,0,0.000000,Sub,17,0,0,43,0,57393,98,632,1
480,481,0,0,0,0.000000e+00,0.000000e+00,0.000000,0,0,0.000000,Sub,17,0,0,13,0,57389,98,526,1
487,488,0,0,0,0.000000e+00,4.504160e-01,0.450416,0,0,0.000000,DMC,7,1,0,65,57410,0,98,497,1
490,491,0,0,1,6.723440e-02,1.208100e+14,0.493696,1,5,0.810406,AMC,12,0,0,84,57411,0,98,499,1
491,492,0,0,7,1.268640e+13,1.860110e+14,0.591474,0,0,0.000000,AML,13,0,0,76,57409,0,98,498,1

In [22]:
# df.loc[filas,columnas]

df.loc[df['substituteIn']>1,'substituteIn'] = np.nan
df.loc[df['substituteOut']>1,'substituteOut'] = np.nan

In [19]:
df

,idappearances,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assist,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,games_gamesID,players_playerID,leagues_leagueID
0,1,0,0,0,0.000000,0.000000e+00,0.000000e+00,0,0,0.000000,GK,1,0,0,90,0.0,0,81,560,1
1,2,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,1,0.106513,DR,2,0,0,82,NaN,0,81,557,1
2,3,0,0,0,0.000000,1.277380e-01,1.277380e-01,0,0,0.000000,DC,3,0,0,90,0.0,0,81,548,1
3,4,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,0,0.000000,DC,3,0,0,90,0.0,0,81,628,1
4,5,0,0,0,0.000000,2.122470e-02,2.122470e-02,0,0,0.000000,DL,4,0,0,90,0.0,0,81,1006,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,0,0,2,0.124260,2.644150e-01,1.401540e-01,0,0,0.000000,Sub,17,0,0,25,0.0,57403,98,966,1
496,497,0,0,0,0.000000,6.133210e-01,6.133210e-01,0,0,0.000000,GK,1,0,0,90,0.0,0,99,609,1
497,498,0,0,0,0.000000,9.684590e-02,9.684590e-02,0,0,0.000000,DR,2,0,0,90,0.0,0,99,625,1
498,499,0,0,1,0.358843,1.147160e+13,1.147160e+13,0,0,0.000000,DC,3,1,0,90,0.0,0,99,626,1
499,500,1,0,1,0.069107,8.224680e-01,8.224680e-01,0,0,0.000000,DC,3,1,0,90,0.0,0,99,612,1

In [23]:
df.isna().sum()

idappearances         0
goals                 0
ownGoals              0
shots                 0
xGoals                0
xGoalsChain           0
xGoalsBuildup         0
assist                0
keyPasses             0
xAssists              0
position              0
positionOrder         0
yellowCard            0
redCard               0
time                  0
substituteIn        100
substituteOut       100
games_gamesID         0
players_playerID      0
leagues_leagueID      0
dtype: int64

In [26]:
df.fillna(df.median(numeric_only = True)[['substituteIn','substituteOut']])

,idappearances,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assist,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,games_gamesID,players_playerID,leagues_leagueID
0,1,0,0,0,0.000000,0.000000e+00,0.000000e+00,0,0,0.000000,GK,1,0,0,90,0.0,0.0,81,560,1
1,2,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,1,0.106513,DR,2,0,0,82,0.0,0.0,81,557,1
2,3,0,0,0,0.000000,1.277380e-01,1.277380e-01,0,0,0.000000,DC,3,0,0,90,0.0,0.0,81,548,1
3,4,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,0,0.000000,DC,3,0,0,90,0.0,0.0,81,628,1
4,5,0,0,0,0.000000,2.122470e-02,2.122470e-02,0,0,0.000000,DL,4,0,0,90,0.0,0.0,81,1006,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,0,0,2,0.124260,2.644150e-01,1.401540e-01,0,0,0.000000,Sub,17,0,0,25,0.0,0.0,98,966,1
496,497,0,0,0,0.000000,6.133210e-01,6.133210e-01,0,0,0.000000,GK,1,0,0,90,0.0,0.0,99,609,1
497,498,0,0,0,0.000000,9.684590e-02,9.684590e-02,0,0,0.000000,DR,2,0,0,90,0.0,0.0,99,625,1
498,499,0,0,1,0.358843,1.147160e+13,1.147160e+13,0,0,0.000000,DC,3,1,0,90,0.0,0.0,99,626,1
499,500,1,0,1,0.069107,8.224680e-01,8.224680e-01,0,0,0.000000,DC,3,1,0,90,0.0,0.0,99,612,1

In [24]:
df.dropna()

,idappearances,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assist,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,games_gamesID,players_playerID,leagues_leagueID
0,1,0,0,0,0.000000,0.000000e+00,0.000000e+00,0,0,0.000000,GK,1,0,0,90,0.0,0.0,81,560,1
2,3,0,0,0,0.000000,1.277380e-01,1.277380e-01,0,0,0.000000,DC,3,0,0,90,0.0,0.0,81,548,1
3,4,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,0,0.000000,DC,3,0,0,90,0.0,0.0,81,628,1
4,5,0,0,0,0.000000,2.122470e-02,2.122470e-02,0,0,0.000000,DL,4,0,0,90,0.0,0.0,81,1006,1
5,6,0,0,0,0.000000,1.636700e-01,1.636700e-01,0,0,0.000000,DMC,7,0,0,90,0.0,0.0,81,551,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,493,1,0,3,0.309258,5.174360e-01,1.409430e-01,0,1,0.067234,FW,15,0,0,90,0.0,0.0,98,502,1
496,497,0,0,0,0.000000,6.133210e-01,6.133210e-01,0,0,0.000000,GK,1,0,0,90,0.0,0.0,99,609,1
497,498,0,0,0,0.000000,9.684590e-02,9.684590e-02,0,0,0.000000,DR,2,0,0,90,0.0,0.0,99,625,1
498,499,0,0,1,0.358843,1.147160e+13,1.147160e+13,0,0,0.000000,DC,3,1,0,90,0.0,0.0,99,626,1
499,500,1,0,1,0.069107,8.224680e-01,8.224680e-01,0,0,0.000000,DC,3,1,0,90,0.0,0.0,99,612,1

In [28]:
df = df.dropna()

In [29]:
df

,idappearances,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assist,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,games_gamesID,players_playerID,leagues_leagueID
0,1,0,0,0,0.000000,0.000000e+00,0.000000e+00,0,0,0.000000,GK,1,0,0,90,0.0,0.0,81,560,1
2,3,0,0,0,0.000000,1.277380e-01,1.277380e-01,0,0,0.000000,DC,3,0,0,90,0.0,0.0,81,548,1
3,4,0,0,0,0.000000,1.065130e-01,1.065130e-01,0,0,0.000000,DC,3,0,0,90,0.0,0.0,81,628,1
4,5,0,0,0,0.000000,2.122470e-02,2.122470e-02,0,0,0.000000,DL,4,0,0,90,0.0,0.0,81,1006,1
5,6,0,0,0,0.000000,1.636700e-01,1.636700e-01,0,0,0.000000,DMC,7,0,0,90,0.0,0.0,81,551,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,493,1,0,3,0.309258,5.174360e-01,1.409430e-01,0,1,0.067234,FW,15,0,0,90,0.0,0.0,98,502,1
496,497,0,0,0,0.000000,6.133210e-01,6.133210e-01,0,0,0.000000,GK,1,0,0,90,0.0,0.0,99,609,1
497,498,0,0,0,0.000000,9.684590e-02,9.684590e-02,0,0,0.000000,DR,2,0,0,90,0.0,0.0,99,625,1
498,499,0,0,1,0.358843,1.147160e+13,1.147160e+13,0,0,0.000000,DC,3,1,0,90,0.0,0.0,99,626,1
499,500,1,0,1,0.069107,8.224680e-01,8.224680e-01,0,0,0.000000,DC,3,1,0,90,0.0,0.0,99,612,1

In [32]:
new_table = df.groupby(by = ['position']).count()

In [38]:
new_table = new_table.reset_index()

In [39]:
new_table

,position,idappearances,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assist,keyPasses,xAssists,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,games_gamesID,players_playerID,leagues_leagueID
0,AMC,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
1,AML,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
2,AMR,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
3,DC,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74
4,DL,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
5,DMC,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
6,DR,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
7,FW,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
8,FWL,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
9,FWR,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
10,GK,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37
11,MC,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
12,ML,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
13,MR,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7

In [41]:
new_table[['position','idappearances','goals','ownGoals','yellowCard','redCard','time']]

   position  idappearances  goals  ownGoals  yellowCard  redCard  time
0       AMC             13     13        13          13       13    13
1       AML              9      9         9           9        9     9
2       AMR             10     10        10          10       10    10
3        DC             74     74        74          74       74    74
4        DL             33     33        33          33       33    33
5       DMC             29     29        29          29       29    29
6        DR             31     31        31          31       31    31
7        FW             23     23        23          23       23    23
8       FWL              2      2         2           2        2     2
9       FWR              1      1         1           1        1     1
10       GK             37     37        37          37       37    37
11       MC             26     26        26          26       26    26
12       ML              5      5         5           5        5     5
13       MR              7      7         7           7        7     7

In [48]:
cnx = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "tQYCnFua9HvCN*E3",
    database = "football_db"
)

cursor = cnx.cursor()

query = 'SELECT * FROM football_db.appearances LIMIT 500;'

cursor.execute(query)

results = cursor.fetchall()

col_names = ['idappearances', 'goals', 'ownGoals', 'shots', 'xGoals', 
             'xGoalsChain', 'xGoalsBuildup', 'assist', 'keyPasses', 
             'xAssists', 'position', 'positionOrder', 'yellowCard', 
             'redCard', 'time', 'substituteIn', 'substituteOut', 
             'games_gamesID', 'players_playerID', 'leagues_leagueID']

data = pd.DataFrame(results, columns = col_names)

df = data.copy()

new_table = preprocessing_data(df)

for index,row in new_table.iterrows():
    tupla = tuple(row)
    query = f"INSERT INTO football_db.resumen(position,idappearances,goals,ownGoals,yellowCard,redCard,time) VALUE ('{tupla[0]}',{tupla[1]},{tupla[2]},{tupla[3]},{tupla[4]},{tupla[5]},{tupla[6]});"
    print("Insertando tupla: ",tupla)
    cursor.execute(query)

cnx.commit()
    
cnx.close()

Insertando tupla:  ('AMC', 13, 13, 13, 13, 13, 13)
Insertando tupla:  ('AML', 9, 9, 9, 9, 9, 9)
Insertando tupla:  ('AMR', 10, 10, 10, 10, 10, 10)
Insertando tupla:  ('DC', 74, 74, 74, 74, 74, 74)
Insertando tupla:  ('DL', 33, 33, 33, 33, 33, 33)
Insertando tupla:  ('DMC', 29, 29, 29, 29, 29, 29)
Insertando tupla:  ('DR', 31, 31, 31, 31, 31, 31)
Insertando tupla:  ('FW', 23, 23, 23, 23, 23, 23)
Insertando tupla:  ('FWL', 2, 2, 2, 2, 2, 2)
Insertando tupla:  ('FWR', 1, 1, 1, 1, 1, 1)
Insertando tupla:  ('GK', 37, 37, 37, 37, 37, 37)
Insertando tupla:  ('MC', 26, 26, 26, 26, 26, 26)
Insertando tupla:  ('ML', 5, 5, 5, 5, 5, 5)
Insertando tupla:  ('MR', 7, 7, 7, 7, 7, 7)

In [43]:
def preprocessing_data(df):
    df.loc[df['substituteIn']>1,'substituteIn'] = np.nan
    df.loc[df['substituteOut']>1,'substituteOut'] = np.nan

    df = df.dropna()

    new_table = df.groupby(by = ['position']).count()

    new_table = new_table.reset_index()

    new_table = new_table[['position','idappearances','goals','ownGoals','yellowCard','redCard','time']]
    
    return new_table